backend:
  name: github
  repo: wslyvh/personal

media_folder: content/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
